name: Must run on customer runner

on: [push]

env:
  NUMERO_N: 1
jobs:
  init:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: control numero
        id: STEP_PROVA
        env: 
          CIAO_MONDO: ciao
        shell: bash
        run: > 
          echo "::set-output name=TAG_NAME::$CIAO_MONDO"
          echo "$TAG_NAME"
      - name: prova
        shell: bash
        run: >  
          echo "${{ steps.STEP_PROVA.outputs.TAG_NAME }}"
     #   if: ${{ env.NUMERO_N == 1 }}
     #   run: |
     #     echo "ok SOCIO"
     # - name: control
   #     shell: bash
     #   if: ${{ env.NUMERO_N == 1 }}
     #   run: | 
     #     echo "uscire!!"
     #     exit 1
     # - name: finish
     #   run: echo "Bella socio"
