name: Must run on customer runner

on: push

jobs:
  init:
    runs-on: ubuntu-latest
    env:
      NUMERO_N: 1
    steps:
      - name: control numero
        if: ${{ evn.NUMERO_N == 1 }}
          - run:|
            echo "ok SOCIO"
      - name: control
        if: ${{ evn.NUMERO_N == 1 }}
          exit 1
      - name: finish
        run: echo "Bella socio"
