name: Must run on customer runner

on: [push]

env:
  NUMERO_N: 1
jobs:
  init:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: control numero
        env:
          URL: https://www.google.com/
        id: STEP_PROVA
        run: |
          echo "::set-output name=RESPONSE_GET_NEXUS::$(curl -s -o /dev/null -w %{http_code} $URL)"
        shell: bash
      - name: prova continuo
        env:
          URL: https://iap.bmwgroup.net/nexus/repository/IAP_Docker_Snapshot/v2/dsa-iam/jwks-auth-service/manifests/1.4.2-SNAPSHOT.eedfbbe
        run: |
          echo ${{ steps.STEP_PROVA.outputs.RESPONSE_GET_NEXUS }}
          chmod +x ./.github/sript/prova.sh
          ./.github/sript/prova.sh ${{ steps.STEP_PROVA.outputs.RESPONSE_GET_NEXUS }} $URL CIAo_SOCIO
#         env: 
#           CIAO_MONDO: ciao
#         run: |
#           echo "::set-output name=TAG_NAME::$CIAO_MONDO"

#       - name: prova
#         shell: bash
#         run: |  
#           echo "${{ steps.STEP_PROVA.outputs.TAG_NAME }}"
#           echo " porva 2 : ${{ steps.STEP_PROVA.env.CIAO_MONDO }}"
     #   if: ${{ env.NUMERO_N == 1 }}
     #   run: |
     #     echo "ok SOCIO"
     # - name: control
   #     shell: bash
     #   if: ${{ env.NUMERO_N == 1 }}
     #   run: | 
     #     echo "uscire!!"
     #     exit 1
     # - name: finish
     #   run: echo "Bella socio"
