name: Must run on customer runner

on: [push]

env:
  NUMERO_N: 1
jobs:
  init:
    runs-on: [ubuntu-latest]
    steps:
      - name: control numero
        run: ./.github/sript/prova.sh
        shell: bash
     #   if: ${{ env.NUMERO_N == 1 }}
     #   run: |
     #     echo "ok SOCIO"
     # - name: control
   #     shell: bash
     #   if: ${{ env.NUMERO_N == 1 }}
     #   run: | 
     #     echo "uscire!!"
     #     exit 1
     # - name: finish
     #   run: echo "Bella socio"
