name: Must run on customer runner

on: [push]

env:
  NUMERO_N: 1
jobs:
  init:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: control numero
        id: STEP_PROVA
        run: |
          chmod +x ./.github/sript/prova.sh
          ./.github/sript/prova.sh
        shell: bash
#         env: 
#           CIAO_MONDO: ciao
#         run: |
#           echo "::set-output name=TAG_NAME::$CIAO_MONDO"
#       - name: prova
#         shell: bash
#         run: |  
#           echo "${{ steps.STEP_PROVA.outputs.TAG_NAME }}"
#           echo " porva 2 : ${{ steps.STEP_PROVA.env.CIAO_MONDO }}"
     #   if: ${{ env.NUMERO_N == 1 }}
     #   run: |
     #     echo "ok SOCIO"
     # - name: control
   #     shell: bash
     #   if: ${{ env.NUMERO_N == 1 }}
     #   run: | 
     #     echo "uscire!!"
     #     exit 1
     # - name: finish
     #   run: echo "Bella socio"
