name: Must run on customer runner

on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: 'Numero'
        required: true
        options:
          - primo-numero
          - secondo-numero

env:
  NUMERO_N: ${{ github.event.inputs.name }}
jobs:
  init:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: kanga333/variable-mapper@master
        with:
          key: ${{ env.NUMERO_N }}
          map: |
            {
              "primo-numero": {
              "env1": "value1",
              "env2": "value2"
              },
            "secondo-numero": {
              "env1": "value1_overwrite",
              "env3": "value3"
              }
            }
      - name: step1
        run: |
          echo ${{ github.event.inputs.name }}
          echo "-- VALORE SOCIO --"
          echo ${{ env.env1 }}
          echo "--------"
#         run: |
#           echo "::set-output name=RESPONSE_GET_NEXUS::$(curl -s -o /dev/null -w %{http_code} $URL)"
#           echo "risposta"
#           echo $RESPONSE_GET_NEXUS
#         shell: bash
#       - name: prova continuo
#         env:
#           URL: https://iap.bmwgroup.net/nexus/repository/IAP_Docker_Snapshot/v2/dsa-iam/jwks-auth-service/manifests/1.4.2-SNAPSHOT.eedfbbe
#         run: |
#           echo ${{ steps.STEP_PROVA.outputs.RESPONSE_GET_NEXUS }}
#           chmod +x ./.github/sript/prova.sh
#           ./.github/sript/prova.sh ${{ steps.STEP_PROVA.outputs.RESPONSE_GET_NEXUS }} $URL CIAo_SOCIO
#         env: 
#           CIAO_MONDO: ciao
#         run: |
#           echo "::set-output name=TAG_NAME::$CIAO_MONDO"

#       - name: prova
#         shell: bash
#         run: |  
#           echo "${{ steps.STEP_PROVA.outputs.TAG_NAME }}"
#           echo " porva 2 : ${{ steps.STEP_PROVA.env.CIAO_MONDO }}"
     #   if: ${{ env.NUMERO_N == 1 }}
     #   run: |
     #     echo "ok SOCIO"
     # - name: control
   #     shell: bash
     #   if: ${{ env.NUMERO_N == 1 }}
     #   run: | 
     #     echo "uscire!!"
     #     exit 1
     # - name: finish
     #   run: echo "Bella socio"
